# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


jobs:
  - job: Linux
    pool:
      vmImage: 'Ubuntu 16.04'
    timeoutInMinutes: 0
    steps:
    - script: |
        ./build-linux-tgz.sh
        cp FRC-*-Linux*.tar.gz $BUILD_ARTIFACTSTAGINGDIRECTORY
      displayName: 'Build the image'
    - task: PublishBuildArtifacts@1
      inputs:
        artifactName: 'LinuxCompiler'

  - job: Windows
    pool:
      vmImage: 'Ubuntu 16.04'
    timeoutInMinutes: 0
    steps:
    - script: |
        ./build-windows.sh
        cp FRC-*-Windows*.zip $BUILD_ARTIFACTSTAGINGDIRECTORY
      displayName: 'Build the image'
    - task: PublishBuildArtifacts@1
      inputs:
        artifactName: 'WindowsCompiler'

  - job: Mac
    pool:
      vmImage: 'xcode9-macos10.13'
    timeoutInMinutes: 0
    steps:
    - script: |
        ./build-mac.sh
        gcp mac/*Toolchain*.tar.gz $BUILD_ARTIFACTSTAGINGDIRECTORY

      displayName: 'Build the image'
    - task: PublishBuildArtifacts@1
      inputs:
        artifactName: 'MacCompiler'
